### ISSUE TITLE
Eror di cordova.cmd build android Pak

### ISSUE THREAD

**Issue by heru-khaerul-cahyana** [IF4008/panduan-praktikum#3]
![Eror build android](https://user-images.githubusercontent.com/71694087/139493650-3170198e-b5a9-4771-aed8-82fe27df8b0d.png)

Izin bertanya pak, di bagian tahap terakhir yaitu build ke android platfrom selalu eror seperti gambar di atas, dan saya sudah mengikuti perintah untuk melakukan download versi jdk sesuai yang di rekomendasikan oleh komen eror tersebut, tetapi tetap saja eror pak.

Dan ini gambar Setup environment variable pada sistem saya.

![envoirment](https://user-images.githubusercontent.com/71694087/139494140-f5b43f82-4665-46e0-b2bb-7a98cbf9c887.png)

Path User Variable

![envoirment user variable](https://user-images.githubusercontent.com/71694087/139494648-17bf4893-42e4-4aaa-a892-514a97a0085f.png)

Kemudian Path System Variabel nya

![Path system variable](https://user-images.githubusercontent.com/71694087/139494842-fa9cb320-f08e-4279-b41d-c0af2557244e.png)

**Comment by yysofiyan** [comment]
@heru-khaerul-cahyana : Path Gradle nya gak ada?

**Comment by heru-khaerul-cahyana** [comment]
Ada Pak, tetapi masih eror nya sama 

![gradle](https://user-images.githubusercontent.com/71694087/139539075-87b8b452-82a0-45c1-b0c3-5ac9a7d71735.png)

**Comment by heru-khaerul-cahyana** [comment]
apakah versi java jdk yang saya instal mempengaruhi pak? saya menginstal jdk versi 1.8.0_311

**Comment by heru-khaerul-cahyana** [comment]
Dan sekarang eror nya seperti ini pak, 

![gradleee](https://user-images.githubusercontent.com/71694087/139541423-b4c00c20-655d-424b-a404-1e1e7c265460.png)

**Comment by yysofiyan** [comment]
@heru-khaerul-cahyana 

Cekt direktori : `"C:\Users\user\AppData\Local\Android\Sdk\build-tools\31.0.0"` (silahkan di sesuaikan)

1. Temukan file bernama` d8.bat.` Ini adalah file batch Windows.
2. Ganti nama `d8.bat` menjadi `dx.bat.`
3. di folder `lib` `("C:\Users\user\AppData\Local\Android\Sdk\build-tools\31.0.0\lib")`
4. Ganti nama` d8.jar` menjadi` dx.jar`
5. Restart Pc/laptop
6. Selanjutnya coba build kembali

`Jika solusi di atas tetep eror silahkan download build-tool 31`

![dx](https://user-images.githubusercontent.com/34052001/139575486-02c29ac4-bcbb-4833-9a45-d8e889cf12f5.jpg)

![rename](https://user-images.githubusercontent.com/34052001/139575489-4737be34-f6c0-49c9-a0ca-567956375000.jpg)

**disini saya pakai build-tool 31**

**Comment by heru-khaerul-cahyana** [comment]
Ketika saya coba testing project app nya, disini menekan button add user tidak berhasil pak dan tidak muncul tampilan user baru dibawahnya seperti yang bapak conthkan, namun ketika data user sama email nya di kosongkan kemudian saya coba add user, itu berhasil dan ada komen alert (masukan nama dan email anda).

![erorhp](https://user-images.githubusercontent.com/71694087/139589562-7d569008-2615-4cde-b99f-312e4c31c041.png)

Dan di Logcat nya saya lihat ada keterangan eror seperti ini pak "I/chromium(21454): [INFO:CONSOLE(45839)] "ERROR TypeError: Cannot read properties of undefined (reading 'executeSql')", source: http://localhost/vendor.js (45839)"

**Comment by heru-khaerul-cahyana** [comment]
> @heru-khaerul-cahyana
> 
> Cekt direktori : `"C:\Users\user\AppData\Local\Android\Sdk\build-tools\31.0.0"` (silahkan di sesuaikan)
> 
> 1. Temukan file bernama` d8.bat.` Ini adalah file batch Windows.
> 2. Ganti nama `d8.bat` menjadi `dx.bat.`
> 3. di folder `lib` `("C:\Users\user\AppData\Local\Android\Sdk\build-tools\31.0.0\lib")`
> 4. Ganti nama` d8.jar` menjadi` dx.jar`
> 5. Restart Pc/laptop
> 6. Selanjutnya coba build kembali
> 
> `Jika solusi di atas tetep eror silahkan download build-tool 31`
> 
> ![dx](https://user-images.githubusercontent.com/34052001/139575486-02c29ac4-bcbb-4833-9a45-d8e889cf12f5.jpg)
> 
> ![rename](https://user-images.githubusercontent.com/34052001/139575489-4737be34-f6c0-49c9-a0ca-567956375000.jpg)
> 
> **disini saya pakai build-tool 31**

**Comment by yysofiyan** [comment]
I/chromium(21454): [INFO:CONSOLE(45839)] "ERROR TypeError: `Cannot read properties of undefined (reading 'executeSql')

maksud dari error tersebut adalah  `Tidak dapat membaca properti yang tidak terdefinisi (reading 'executeSql'))` . coba cek kembali kode koneksi ke database-nya.

**Comment by heru-khaerul-cahyana** [comment]
@yysofiyan  Sudah berhasil tidak ada yang eror lagi pak, terima kasih

**Comment by yysofiyan** [comment]
@heru-khaerul-cahyana 👍 👍
